apiVersion: v1
kind: Secret
metadata:
  name: app-env
  namespace: uploads
type: Opaque
stringData:
  APP_ENV: production
  QUEUE_CONNECTION: redis
  REDIS_HOST: <upload-service-redis.xxxxxx.use1.cache.amazonaws.com> (replace with Terraform output)
  REDIS_PORT: "6379"
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET: your-bucket
