apiVersion: v1
kind: Secret
metadata:
  name: app-env
  namespace: uploads
type: Opaque
stringData:
  APP_ENV: production
  QUEUE_CONNECTION: redis
  REDIS_HOST: redis
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET: your-bucket
