apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-api
  namespace: uploads
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laravel-api
  template:
    metadata:
      labels:
        app: laravel-api
    spec:
      containers:
        - name: api
#          image: "your-dockerhub-username/laravel-api:latest"
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: app-env
          volumeMounts:
            - name: uploads
              mountPath: /var/www/storage/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-efs-pvc




