apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: laravel-api-hpa
  namespace: uploads
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: laravel-api
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Object
      object:
        describedObject:
          kind: ingress
          apiVersion: networking.k8s.io/v1
          name: laravel-api
        target:
          type: AverageValue
          averageValue: 10 # we don't want more than 10rps per replica
        metric:
          name: requests_per_second
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
